# Default values for generative-virtual-screening-chart.
---
replicaCount: 1

diffdock:
  containerName: diffdock
  containerPort: 8000
  tritonPort: 8003
  repository: nvcr.io/nim/mit/diffdock
  tag: "2.0"
  pullPolicy: Always
  cacheFolder: /opt/nim/.cache
  servicePort: 8084
  readinessProbeTimeoutSeconds: 10
  readinessProbePeriodSeconds: 60
genmol:
  containerName: genmol
  containerPort: 8000
  repository: nvcr.io/nim/nvidia/genmol
  tag: "1.0"
  pullPolicy: Always
  cacheFolder: /opt/nim/.cache
  servicePort: 8083
  readinessProbeTimeoutSeconds: 10
  readinessProbePeriodSeconds: 60
msa:
  containerName: msa
  containerPort: 8000
  repository: nvcr.io/nim/colabfold/msa-search
  tag: "1.0"
  pullPolicy: Always
  cacheFolder: /opt/nim/.cache
  servicePort: 8081
  readinessProbeTimeoutSeconds: 10
  readinessProbePeriodSeconds: 60
openfold2:
  containerName: openfold2
  containerPort: 8000
  repository: nvcr.io/nim/openfold/openfold2
  tag: "1.0"
  pullPolicy: Always
  cacheFolder: /opt/nim/.cache
  servicePort: 8082
  readinessProbeTimeoutSeconds: 10
  readinessProbePeriodSeconds: 60

imagePullSecret:
  registry: "nvcr.io"
  name: "ngc-secret-docker-registry"
  create: false
  username: '$oauthtoken'
  secretName: ngc-secret-docker-registry
  secretKey: NGC_API_KEY

apiSecret:
  name: "ngc-registry-secret"
  secretName: ngc-registry-secret
  secretKey: NGC_REGISTRY_KEY

service:
  type: ClusterIP

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    nvidia.com/gpu: 1
  requests:
    nvidia.com/gpu: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

persistence:
  enabled: true
  existingClaim: ""
  storageClass: standard
  accessMode: ReadWriteMany
  hostPath: /data/nim
  size: 1.5Ti

nodeSelector: {}

tolerations: []

affinity: {}
